import { Ionicons } from '@expo/vector-icons';
import { Stack, useFocusEffect, useRouter } from 'expo-router';
import React, { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useChild } from '../../lib/SelectedChildContext';
import { deleteEmergencyContact, loadEmergencyContacts, saveEmergencyContact, type SafetyEmergencyContact } from '../../lib/safety/preparednessData';
import { getSafetyAccess } from '../../lib/safety/safetyAccess';

type Draft = { name: string; relationship: string; phone: string; email: string; notes: string; isPrimary: boolean };
const EMPTY: Draft = { name: '', relationship: '', phone: '', email: '', notes: '', isPrimary: false };

export default function EmergencyContactsScreen() {
  const router = useRouter(); const { selectedChild } = useChild(); const childId = selectedChild?.id;
  const [contacts, setContacts] = useState<SafetyEmergencyContact[]>([]); const [canEdit, setCanEdit] = useState(false); const [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState<SafetyEmergencyContact | null | undefined>(undefined); const [draft, setDraft] = useState<Draft>(EMPTY); const [saving, setSaving] = useState(false);
  const refresh = useCallback(async () => { if (!childId) { setLoading(false); return; } setLoading(true); try { const [items, access] = await Promise.all([loadEmergencyContacts(childId), getSafetyAccess(childId)]); setContacts(items); setCanEdit(access.canEditSafetyProfile); } catch { Alert.alert('Contacts Unavailable', 'We couldn’t load emergency contacts right now.'); } finally { setLoading(false); } }, [childId]);
  useFocusEffect(useCallback(() => { void refresh(); }, [refresh]));
  const open = (contact?: SafetyEmergencyContact) => { setEditing(contact ?? null); setDraft(contact ? { name: contact.name, relationship: contact.relationship ?? '', phone: contact.phone ?? '', email: contact.email ?? '', notes: contact.notes ?? '', isPrimary: contact.isPrimary } : EMPTY); };
  const save = async () => { if (!childId || !draft.name.trim() || (!draft.phone.trim() && !draft.email.trim())) { Alert.alert('Add contact details', 'Enter a name and at least a phone number or email address.'); return; } setSaving(true); try { await saveEmergencyContact(childId, draft, editing?.id); setEditing(undefined); await refresh(); } catch { Alert.alert('Contact Not Saved', 'We couldn’t save this contact right now.'); } finally { setSaving(false); } };
  const remove = (contact: SafetyEmergencyContact) => Alert.alert('Delete emergency contact?', `${contact.name} will be removed from this child’s Safety Profile.`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => { if (!childId) return; void deleteEmergencyContact(childId, contact.id).then(refresh).catch(() => Alert.alert('Contact Not Deleted', 'Please try again.')); } }]);

  return <SafeAreaView style={styles.container}><Stack.Screen options={{ headerShown: false }} /><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}>
    <Pressable accessibilityRole="button" accessibilityLabel="Back to Safety" onPress={() => router.canGoBack() ? router.back() : router.replace('/safety')} style={styles.back}><Ionicons name="chevron-back" size={24} color="#3F3B47" accessible={false} /></Pressable>
    <Text accessibilityRole="header" style={styles.title}>Emergency Contacts</Text><Text style={styles.subtitle}>Add the people you may need to reach quickly.</Text>
    {loading ? <ActivityIndicator style={styles.loading} color="#7256B6" /> : editing !== undefined ? <View style={styles.form}>
      <Field label="Name" value={draft.name} maxLength={100} onChangeText={(name) => setDraft({ ...draft, name })} />
      <Field label="Relationship (optional)" value={draft.relationship} maxLength={100} onChangeText={(relationship) => setDraft({ ...draft, relationship })} />
      <Field label="Phone" value={draft.phone} maxLength={40} keyboardType="phone-pad" onChangeText={(phone) => setDraft({ ...draft, phone })} />
      <Field label="Email" value={draft.email} maxLength={254} keyboardType="email-address" autoCapitalize="none" onChangeText={(email) => setDraft({ ...draft, email })} />
      <View style={styles.toggleRow}><View style={styles.toggleCopy}><Text style={styles.label}>Primary emergency contact</Text><Text style={styles.helper}>Shown first in emergency information.</Text></View><Switch accessibilityLabel="Primary emergency contact" value={draft.isPrimary} onValueChange={(isPrimary) => setDraft({ ...draft, isPrimary })} /></View>
      <Field label="Optional note" value={draft.notes} maxLength={300} multiline onChangeText={(notes) => setDraft({ ...draft, notes })} />
      <Pressable accessibilityRole="button" accessibilityState={{ busy: saving, disabled: saving }} disabled={saving} onPress={() => void save()} style={styles.primary}>{saving ? <ActivityIndicator color="#FFF" /> : <Text style={styles.primaryText}>Save Contact</Text>}</Pressable>
      <Pressable accessibilityRole="button" onPress={() => setEditing(undefined)} style={styles.secondary}><Text style={styles.secondaryText}>Cancel</Text></Pressable>
    </View> : <>
      {!contacts.length ? <View style={styles.empty}><Ionicons name="call-outline" size={30} color="#4178A8" /><Text style={styles.emptyTitle}>No emergency contacts yet</Text><Text style={styles.emptyText}>Add someone your family may need to reach quickly.</Text></View> : contacts.map((contact) => <View key={contact.id} style={styles.card}><View style={styles.cardHeader}><Text style={styles.cardName}>{contact.name}</Text>{contact.isPrimary ? <Text style={styles.badge}>PRIMARY</Text> : null}</View>{contact.relationship ? <Text style={styles.cardMeta}>{contact.relationship}</Text> : null}{contact.phone ? <Text style={styles.cardDetail}>{contact.phone}</Text> : null}{contact.email ? <Text style={styles.cardDetail}>{contact.email}</Text> : null}{canEdit ? <View style={styles.actions}><Pressable accessibilityRole="button" accessibilityLabel={`Edit ${contact.name}`} onPress={() => open(contact)}><Text style={styles.actionText}>Edit</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel={`Delete ${contact.name}`} onPress={() => remove(contact)}><Text style={styles.deleteText}>Delete</Text></Pressable></View> : null}</View>)}
      {canEdit ? <Pressable accessibilityRole="button" onPress={() => open()} style={styles.primary}><Text style={styles.primaryText}>Add Emergency Contact</Text></Pressable> : null}
    </>}
  </ScrollView></KeyboardAvoidingView></SafeAreaView>;
}

function Field({ label, ...props }: React.ComponentProps<typeof TextInput> & { label: string }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput accessibilityLabel={label} placeholderTextColor="#918A96" style={[styles.input, props.multiline && styles.multiline]} {...props} /></View>; }
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#F7F5FA' }, flex: { flex: 1 }, content: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 100 }, back: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF', borderWidth: 1, borderColor: '#ECE8F0' }, title: { marginTop: 22, color: '#292631', fontSize: 30, lineHeight: 38, fontWeight: '900' }, subtitle: { marginTop: 8, color: '#706A76', fontSize: 16, lineHeight: 24, fontWeight: '600' }, loading: { marginTop: 50 }, empty: { marginTop: 24, padding: 28, borderRadius: 26, alignItems: 'center', backgroundColor: '#FFF', borderWidth: 1, borderColor: '#E9E5ED' }, emptyTitle: { marginTop: 12, color: '#39333F', fontSize: 18, fontWeight: '900' }, emptyText: { marginTop: 7, color: '#77707C', fontSize: 14, lineHeight: 21, textAlign: 'center' }, card: { marginTop: 14, padding: 18, borderRadius: 22, backgroundColor: '#FFF', borderWidth: 1, borderColor: '#E9E5ED' }, cardHeader: { flexDirection: 'row', gap: 10, alignItems: 'center' }, cardName: { flex: 1, color: '#37313D', fontSize: 18, lineHeight: 24, fontWeight: '900' }, badge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 10, color: '#5D477E', backgroundColor: '#EEE8FA', fontSize: 10, fontWeight: '900' }, cardMeta: { marginTop: 4, color: '#716A77', fontSize: 14, fontWeight: '700' }, cardDetail: { marginTop: 7, color: '#4F4855', fontSize: 15, lineHeight: 21 }, actions: { marginTop: 14, flexDirection: 'row', gap: 24 }, actionText: { color: '#6B4EAD', fontSize: 14, fontWeight: '900' }, deleteText: { color: '#A24F49', fontSize: 14, fontWeight: '900' }, primary: { minHeight: 58, marginTop: 20, paddingHorizontal: 20, borderRadius: 29, alignItems: 'center', justifyContent: 'center', backgroundColor: '#7256B6' }, primaryText: { color: '#FFF', fontSize: 16, fontWeight: '900' }, secondary: { minHeight: 52, marginTop: 10, alignItems: 'center', justifyContent: 'center' }, secondaryText: { color: '#6B4EAD', fontSize: 15, fontWeight: '900' }, form: { marginTop: 12 }, field: { marginTop: 16 }, label: { color: '#443D49', fontSize: 14, lineHeight: 20, fontWeight: '800' }, input: { minHeight: 54, marginTop: 7, paddingHorizontal: 15, borderRadius: 17, color: '#29232E', backgroundColor: '#FFF', borderWidth: 1, borderColor: '#DED8E2', fontSize: 16 }, multiline: { minHeight: 104, paddingTop: 14, textAlignVertical: 'top' }, toggleRow: { minHeight: 66, marginTop: 18, flexDirection: 'row', alignItems: 'center' }, toggleCopy: { flex: 1, paddingRight: 12 }, helper: { marginTop: 3, color: '#7D7582', fontSize: 12, lineHeight: 18 } });
