import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { approveMetadataBatch, clientValidation, getAllProductionReviewDecisions, getMetadataReviewRows, type LessonMetadataReviewRow, type ProductionReviewDecision } from '../../lib/personalization/metadataReview';

const FILTERS=['all','candidate','needs_review','approved','needs_changes','rejected'] as const;
const FLAGS=['all','communication','safety','both','duplicate','none'] as const;
const TIERS=['all','quick_confirmation','focused_review','detailed_review','content_dependent'] as const;
export default function PersonalizationReviewScreen(){
 const router=useRouter(); const [rows,setRows]=useState<LessonMetadataReviewRow[]>([]); const [loading,setLoading]=useState(true);
 const [decisions,setDecisions]=useState<ProductionReviewDecision[]>([]);
 const [search,setSearch]=useState(''); const [status,setStatus]=useState<(typeof FILTERS)[number]>('all'); const [flag,setFlag]=useState<(typeof FLAGS)[number]>('all'); const [tier,setTier]=useState<(typeof TIERS)[number]>('all'); const [content,setContent]=useState('all'); const [entitlement,setEntitlement]=useState('all'); const [selected,setSelected]=useState<Set<string>>(new Set());
 const load=useCallback(async()=>{setLoading(true);try{const [metadata,reviewDecisions]=await Promise.all([getMetadataReviewRows(),getAllProductionReviewDecisions()]);setRows(metadata);setDecisions(reviewDecisions);}catch(e){Alert.alert('Unable to load metadata',e instanceof Error?e.message:'Unknown error');}finally{setLoading(false);}},[]);
 useFocusEffect(useCallback(()=>{void load();},[load]));
 const has=(r:LessonMetadataReviewRow,v:string)=>r.candidate_warnings.includes(v);
 const filtered=useMemo(()=>rows.filter(r=>{
  const comm=has(r,'COMMUNICATION_REVIEW_REQUIRED'),safe=has(r,'SAFETY_REVIEW_REQUIRED'),dup=has(r,'DUPLICATE_REVIEW');
  return (!search||r.lesson.title.toLowerCase().includes(search.toLowerCase()))&&(status==='all'||r.review_status===status)&&(tier==='all'||r.review_tier===tier)&&(content==='all'||(content==='current_production'?r.lesson.quality_status==='approved'&&r.lesson.is_active:r.lesson.quality_status===content))&&(entitlement==='all'||(entitlement==='pro'?r.lesson.pro_only:!r.lesson.pro_only))&&(flag==='all'||(flag==='communication'&&comm&&!safe)||(flag==='safety'&&safe&&!comm)||(flag==='both'&&comm&&safe)||(flag==='duplicate'&&dup)||(flag==='none'&&!comm&&!safe&&!dup));
 }),[rows,search,status,tier,content,entitlement,flag]);
 const safeEligible=(r:LessonMetadataReviewRow)=>r.review_tier==='quick_confirmation'&&clientValidation(r).length===0&&r.candidate_confidence!=='LOW';
 const approve=async()=>{const ids=[...selected];if(!ids.length)return;Alert.alert('Approve safe metadata',`${ids.length} selected. Only records still valid and fully resolved will be approved.`,[{text:'Cancel',style:'cancel'},{text:'Approve',onPress:async()=>{try{const result=await approveMetadataBatch(ids);Alert.alert('Batch result',`Approved: ${result.approved}\nSkipped: ${result.skipped}\nFailed: ${result.failed}`);setSelected(new Set());await load();}catch(e){Alert.alert('Batch failed',e instanceof Error?e.message:'Unknown error');}}}]);};
 const productionRows=rows.filter(r=>r.lesson.quality_status==='approved'&&r.lesson.is_active);const unresolvedByMetadata=new Map<string,number>();decisions.filter(d=>(d.requires_human&&!['human_confirmed','human_edited'].includes(d.decision_status))||d.decision_status==='content_dependent').forEach(d=>unresolvedByMetadata.set(d.metadata_id,(unresolvedByMetadata.get(d.metadata_id)??0)+1));
 const stats={production:productionRows.length,ready:productionRows.filter(r=>(unresolvedByMetadata.get(r.id)??0)===0).length,one:productionRows.filter(r=>unresolvedByMetadata.get(r.id)===1).length,two:productionRows.filter(r=>unresolvedByMetadata.get(r.id)===2).length,'3+':productionRows.filter(r=>(unresolvedByMetadata.get(r.id)??0)>=3).length,approved:productionRows.filter(r=>r.review_status==='approved').length};
 return <SafeAreaView style={s.root}><ScrollView contentContainerStyle={s.content}>
  <View style={s.header}><TouchableOpacity onPress={()=>router.back()}><Ionicons name="arrow-back" size={24} color="#29145F"/></TouchableOpacity><View style={{flex:1}}><Text style={s.title}>Personalization Review</Text><Text style={s.sub}>Review hidden drafts before atomic lesson and metadata approval.</Text></View></View>
  <View style={s.stats}>{Object.entries(stats).map(([k,v])=><View key={k} style={s.stat}><Text style={s.statN}>{v}</Text><Text style={s.statL}>{k}</Text></View>)}</View>
  <TextInput style={s.search} value={search} onChangeText={setSearch} placeholder="Search lesson title"/>
  <Filter label="Review tier" values={TIERS} value={tier} setValue={v=>setTier(v as typeof tier)}/><Filter label="Review status" values={FILTERS} value={status} setValue={v=>setStatus(v as typeof status)}/><Filter label="Exceptions" values={FLAGS} value={flag} setValue={v=>setFlag(v as typeof flag)}/><Filter label="Content scope" values={['all','current_production','approved','draft','needs_revision']} value={content} setValue={setContent}/><Filter label="Entitlement" values={['all','free','pro']} value={entitlement} setValue={setEntitlement}/>
  <View style={s.resultRow}><Text style={s.result}>{filtered.length} of {rows.length}</Text><TouchableOpacity style={[s.batch,!selected.size&&s.disabled]} disabled={!selected.size} onPress={approve}><Text style={s.batchText}>Approve selected ({selected.size})</Text></TouchableOpacity></View>
  {loading?<ActivityIndicator color="#7C3AED"/>:filtered.map(r=>{const eligible=safeEligible(r),isSelected=selected.has(r.id);return <TouchableOpacity key={r.id} style={s.card} onPress={()=>router.push({pathname:'/admin/personalization-review/[id]',params:{id:r.id}} as never)}>
   <View style={s.cardTop}><TouchableOpacity disabled={!eligible} onPress={(e)=>{e.stopPropagation();const next=new Set(selected);if(isSelected)next.delete(r.id);else next.add(r.id);setSelected(next);}}><Ionicons name={isSelected?'checkbox':'square-outline'} size={24} color={eligible?'#7C3AED':'#CBD5E1'}/></TouchableOpacity><View style={{flex:1}}><Text style={s.cardTitle}>{r.lesson.title}</Text><Text style={s.meta}>{r.lesson.category} · {r.lesson.skill_area} · Stage {r.lesson.stage_number}</Text></View><Status value={r.review_status}/></View>
   <View style={s.tags}><Tag t={r.review_tier.replace('_',' ')}/><Tag t={r.candidate_confidence??'UNKNOWN'}/><Tag t={r.lesson.quality_status??'unknown'}/>{has(r,'COMMUNICATION_REVIEW_REQUIRED')&&<Tag t="communication" warn/>}{has(r,'SAFETY_REVIEW_REQUIRED')&&<Tag t="safety" warn/>}{has(r,'DUPLICATE_REVIEW')&&<Tag t="duplicate" warn/>}<Tag t={`${clientValidation(r).length} blockers`} warn={clientValidation(r).length>0}/></View>
   <Text style={s.summary}>Target: {r.target_skill_code} · Mastery: {r.mastery_group}</Text><Text style={s.summary}>Responses: {r.supported_response_modes.join(', ')||'none explicit'}</Text><Text style={s.summary}>Needs: {r.assessment_need_tags.join(', ')||'none'} · Materials: {r.material_activity_tags.join(', ')||'none'}</Text><Text style={(unresolvedByMetadata.get(r.id)??0)===0&&r.support_level_reviewed&&r.content_review_status==='approved'?s.clean:s.pending}>{decisions.filter(d=>d.metadata_id===r.id).length===0?'Needs personalization decisions':(unresolvedByMetadata.get(r.id)??0)>0?`${unresolvedByMetadata.get(r.id)} decision${unresolvedByMetadata.get(r.id)===1?'':'s'} incomplete`:!r.support_level_reviewed?'Support level needs review':r.content_review_status!=='approved'?'Content review confirmation needed':r.lesson.quality_status==='approved'?'Approved':'Ready for final approval'}</Text>
  </TouchableOpacity>})}
 </ScrollView></SafeAreaView>;
}
function Filter({label,values,value,setValue}:{label:string;values:readonly string[];value:string;setValue:(v:string)=>void}){return <View><Text style={s.filterLabel}>{label}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{values.map(v=><TouchableOpacity key={v} style={[s.pill,value===v&&s.pillOn]} onPress={()=>setValue(v)}><Text style={[s.pillText,value===v&&s.pillTextOn]}>{v.replace('_',' ')}</Text></TouchableOpacity>)}</ScrollView></View>}
function Tag({t,warn=false}:{t:string;warn?:boolean}){return <View style={[s.tag,warn&&s.tagWarn]}><Text style={s.tagText}>{t}</Text></View>}; function Status({value}:{value:string}){return <View style={s.status}><Text style={s.statusText}>{value.replace('_',' ')}</Text></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#FFF8F1'},content:{padding:20,paddingBottom:100},header:{flexDirection:'row',gap:14,alignItems:'center',marginBottom:18},title:{fontSize:25,fontWeight:'900',color:'#29145F'},sub:{color:'#64748B',fontWeight:'600'},stats:{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:14},stat:{backgroundColor:'#FFF',borderRadius:14,padding:10,minWidth:82,borderWidth:1,borderColor:'#EDE9FE'},statN:{fontSize:20,fontWeight:'900',color:'#6D28D9'},statL:{fontSize:11,color:'#64748B',textTransform:'capitalize'},search:{backgroundColor:'#FFF',borderWidth:1,borderColor:'#DDD6FE',borderRadius:14,padding:13,marginBottom:12},filterLabel:{fontWeight:'800',color:'#475569',marginTop:8,marginBottom:6},pill:{paddingHorizontal:12,paddingVertical:8,borderRadius:999,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0',marginRight:7},pillOn:{backgroundColor:'#6D28D9',borderColor:'#6D28D9'},pillText:{fontSize:12,fontWeight:'800',color:'#475569',textTransform:'capitalize'},pillTextOn:{color:'#FFF'},resultRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginVertical:16},result:{fontWeight:'900',color:'#334155'},batch:{backgroundColor:'#6D28D9',borderRadius:12,padding:11},disabled:{opacity:.4},batchText:{color:'#FFF',fontWeight:'900'},card:{backgroundColor:'#FFF',padding:15,borderRadius:18,marginBottom:10,borderWidth:1,borderColor:'#EDE9FE'},cardTop:{flexDirection:'row',gap:10,alignItems:'flex-start'},cardTitle:{fontSize:16,fontWeight:'900',color:'#29145F'},meta:{fontSize:12,color:'#64748B',marginTop:3},summary:{fontSize:11,color:'#475569',marginTop:5},clean:{fontSize:11,color:'#047857',fontWeight:'800',marginTop:7},pending:{fontSize:11,color:'#B45309',fontWeight:'800',marginTop:7},tags:{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:10},tag:{backgroundColor:'#ECFDF5',borderRadius:999,paddingHorizontal:8,paddingVertical:4},tagWarn:{backgroundColor:'#FEF3C7'},tagText:{fontSize:10,fontWeight:'800',color:'#475569'},status:{backgroundColor:'#EDE9FE',paddingHorizontal:8,paddingVertical:5,borderRadius:999},statusText:{fontSize:10,fontWeight:'900',color:'#6D28D9',textTransform:'capitalize'}});
