import candidateArtifact from '../../../data/lesson-metadata-candidates.json';
import type { LessonLibraryItem } from '../../lessonLibrary';
import { supabase } from '../../supabase';
import type { CommunicationMode } from '../types';
import type { CandidateMetadata,CurriculumPlacement,MetadataSource,ShadowLessonCandidate } from './types';

const artifactByLessonId=new Map(candidateArtifact.candidates.map(c=>[c.lesson_id,c]));
const arr=(v:unknown)=>Array.isArray(v)?v.map(String):[];
function artifactMetadata(id:string):CandidateMetadata|null{const c=artifactByLessonId.get(id);if(!c)return null;return{targetSkillCode:c.proposed.target_skill_code,masteryGroup:c.proposed.mastery_group,skillStageCode:c.proposed.skill_stage_code,prerequisiteSkillCodes:c.proposed.prerequisite_skill_codes,assessmentNeedTags:c.proposed.assessment_need_tags,supportedResponseModes:c.proposed.supported_response_modes as CommunicationMode[],contraindicationTags:c.proposed.contraindication_tags,materialActivityTags:c.proposed.material_activity_tags,personalizationMetadataVersion:c.proposed.personalization_metadata_version,supportLevel:null,supportLevelReviewed:false,status:'candidate_unreviewed',source:'candidate_artifact',currentFingerprint:false,fiveDecisionsComplete:false,recommendationReady:false,confidence:c.review.overall_confidence as CandidateMetadata['confidence']};}
function liveMetadata(row:any,decisionCount:number,unresolved:number):CandidateMetadata{const approved=row.review_status==='approved';const current=!row.metadata_stale&&Boolean(row.content_fingerprint)&&(!approved||row.approved_content_fingerprint===row.content_fingerprint);return{targetSkillCode:row.target_skill_code,masteryGroup:row.mastery_group,skillStageCode:row.skill_stage_code,prerequisiteSkillCodes:arr(row.prerequisite_skill_codes),assessmentNeedTags:arr(row.assessment_need_tags),supportedResponseModes:arr(row.supported_response_modes) as CommunicationMode[],contraindicationTags:arr(row.contraindication_tags),materialActivityTags:arr(row.material_activity_tags),personalizationMetadataVersion:row.metadata_version,supportLevel:row.support_level,supportLevelReviewed:Boolean(row.support_level_reviewed),status:approved?'approved':'reviewed',source:approved?'approved_live':'reviewed_live',currentFingerprint:current,fiveDecisionsComplete:decisionCount===5&&unresolved===0,recommendationReady:approved&&current&&decisionCount===5&&unresolved===0&&row.support_level_reviewed&&row.content_review_status==='approved',confidence:row.candidate_confidence};}
export function resolveShadowMetadata(id:string,live:any|null,decisionCount=0,unresolved=0):CandidateMetadata{if(live&&['approved','reviewed'].includes(live.review_status)){const resolved=liveMetadata(live,decisionCount,unresolved);if(resolved.status==='approved'||resolved.status==='reviewed')return resolved;}return artifactMetadata(id)??{targetSkillCode:null,masteryGroup:null,skillStageCode:null,prerequisiteSkillCodes:[],assessmentNeedTags:[],supportedResponseModes:[],contraindicationTags:[],materialActivityTags:[],personalizationMetadataVersion:null,supportLevel:null,supportLevelReviewed:false,status:'missing',source:'unavailable',currentFingerprint:false,fiveDecisionsComplete:false,recommendationReady:false,confidence:null};}
const emptyPlacement:CurriculumPlacement={domainKey:null,skillKey:null,stageDefinitionId:null,stageNumber:null,stageName:null,mappingStatus:null,mappingConfidence:null,contentDisposition:null,sensitivity:null,recommendationEligibility:null,timeRelevance:'unresolved',ownerDecisionRequired:false,isActivePrimary:false};
export async function loadShadowLessonCandidates():Promise<ShadowLessonCandidate[]>{
 const [lessons,mappings,metadata,decisions]=await Promise.all([
  supabase.from('lesson_library').select('*').order('created_at'),
  supabase.from('lesson_curriculum_mappings').select('lesson_id,domain_key,skill_key,stage_definition_id,mapping_status,mapping_confidence,content_disposition,sensitivity,recommendation_eligibility,time_of_day_relevance,owner_decision_required,is_active_primary'),
  supabase.from('lesson_personalization_metadata').select('*'),
  supabase.from('lesson_personalization_review_decisions').select('lesson_id,decision_status'),
 ]); for(const r of [lessons,mappings,metadata,decisions])if(r.error)throw r.error;
 const mapBy=new Map((mappings.data??[]).map((m:any)=>[m.lesson_id,m])),metaBy=new Map((metadata.data??[]).map((m:any)=>[m.lesson_id,m]));const decisionBy=new Map<string,{count:number;unresolved:number}>();
 for(const d of decisions.data??[]){const x=decisionBy.get(d.lesson_id)??{count:0,unresolved:0};x.count++;if(!['resolved_deterministic','human_confirmed','human_edited'].includes(d.decision_status))x.unresolved++;decisionBy.set(d.lesson_id,x);}
 return ((lessons.data??[]) as LessonLibraryItem[]).map(lesson=>{const m:any=mapBy.get(lesson.id),live:any=metaBy.get(lesson.id),ds=decisionBy.get(lesson.id)??{count:0,unresolved:0};const md=resolveShadowMetadata(lesson.id,live,ds.count,ds.unresolved);const curriculum=m?{domainKey:m.domain_key,skillKey:m.skill_key,stageDefinitionId:m.stage_definition_id,stageNumber:lesson.stage_number,stageName:lesson.stage_name,mappingStatus:m.mapping_status,mappingConfidence:m.mapping_confidence,contentDisposition:m.content_disposition,sensitivity:m.sensitivity,recommendationEligibility:m.recommendation_eligibility,timeRelevance:m.time_of_day_relevance??'unresolved',ownerDecisionRequired:Boolean(m.owner_decision_required),isActivePrimary:Boolean(m.is_active_primary)}:emptyPlacement;const missing=['targetSkillCode','masteryGroup','skillStageCode'].filter(k=>!md[k as keyof CandidateMetadata]);return{lesson,metadata:md,curriculum,missingMetadata:missing};});
}
export function countMetadataSources(rows:ShadowLessonCandidate[]){return rows.reduce((a,r)=>{a[r.metadata.source]++;return a;},{approved_live:0,reviewed_live:0,candidate_artifact:0,unavailable:0} as Record<MetadataSource,number>);}
