import type { PersonalizedRecommendationContext,ShadowLessonCandidate,ShadowRecommendationOptions } from './types';
const RETIRED=new Set(['practice clear sounds','say the whole word','clear speech everywhere','try one new bite']);
const ok=(filter:string,accepted:boolean,reason:string)=>({filter,accepted,reason});
export function evaluateEligibility(c:ShadowLessonCandidate,ctx:PersonalizedRecommendationContext,o:ShadowRecommendationOptions){const d=[] as ReturnType<typeof ok>[];
 d.push(ok('active',c.lesson.is_active,'Lesson must be active.'));d.push(ok('approval',c.lesson.quality_status==='approved','Lesson content must be approved.'));d.push(ok('entitlement',o.isPro||!c.lesson.pro_only,'Current entitlement must permit delivery.'));
 d.push(ok('mapping',Boolean(c.curriculum.domainKey&&c.curriculum.skillKey&&c.curriculum.stageDefinitionId)&&c.curriculum.mappingStatus!=='unresolved','Authoritative shadow placement must be resolved.'));d.push(ok('recommendation_eligibility',c.curriculum.recommendationEligibility==='shadow_candidate','Mapping must explicitly permit shadow candidacy.'));
 d.push(ok('retirement',!RETIRED.has(c.lesson.title.toLowerCase())&&!['retired','excluded','fallback'].includes(c.curriculum.contentDisposition??''),'Retired, excluded, and fallback concepts are ineligible.'));d.push(ok('owner_decision',!c.curriculum.ownerDecisionRequired,'Unresolved owner decisions are excluded.'));d.push(ok('metadata_ready',c.metadata.recommendationReady,'Normal ranking requires current approved live metadata and five complete decisions.'));
 const modes=ctx.profile.communication.modes,supported=c.metadata.supportedResponseModes;d.push(ok('communication',!modes.length||!supported.length||modes.some(m=>supported.includes(m)),'At least one established communication method must be supported when modes are constrained.'));
 const conflicts=ctx.profile.restrictions.tags.filter(t=>c.metadata.contraindicationTags.includes(t)||c.metadata.materialActivityTags.includes(t));d.push(ok('restrictions',conflicts.length===0,conflicts.length?`Controlled restriction conflict: ${conflicts.join(', ')}`:'No controlled restriction conflict.'));
 const missing=c.metadata.prerequisiteSkillCodes.filter(x=>!ctx.profile.lessonState.masteredSkillCodes.includes(x));d.push(ok('prerequisites',missing.length===0,missing.length?`Unmet hard prerequisite: ${missing.join(', ')}`:'No unmet hard prerequisite.'));if(c.curriculum.sensitivity==='high_scrutiny')d.push(ok('high_scrutiny',c.metadata.source==='approved_live'&&c.metadata.recommendationReady,'High-scrutiny lessons require current approved live review.'));return d;}
