import { getRecommendedStageForSkill } from '../../lessonProgression';
import { getMasteredSkills } from '../../lessonRecommendations';
import { getRecommendedLesson } from '../../lessonLibrary';
import { SKILL_PROGRESSION_PATHS } from '../../lessonTypes';
import { getSmartRecommendedSkill } from '../../smartLessonRecommendations';
import { inspectPersonalizationProfile } from '../inspectProfile';
import { countMetadataSources,loadShadowLessonCandidates } from './candidates';
import { buildPersonalizedRecommendationContext } from './context';
import { evaluateEligibility } from './eligibility';
import { scoreShadowCandidate } from './scoring';
import { SHADOW_ALGORITHM_VERSION,type EvaluatedCandidate,type ShadowRecommendationOptions,type ShadowRecommendationResult } from './types';

export async function getCurrentProductionRecommendation(childId:string,options:Pick<ShadowRecommendationOptions,'category'|'isPro'>){const category=options.category??'Communication';const available=SKILL_PROGRESSION_PATHS[category]||[];const skillArea=available.length?await getSmartRecommendedSkill(childId,available):undefined;const stageNumber=skillArea?await getRecommendedStageForSkill({childId,category,skillArea}):undefined;const mastered=await getMasteredSkills(childId);const lesson=await getRecommendedLesson({category,skillArea,stageNumber,childId,excludeSkills:mastered,isPro:options.isPro});return{lesson,skillArea,stageNumber};}
export async function getShadowRecommendation(childId:string,o:ShadowRecommendationOptions):Promise<ShadowRecommendationResult>{if(o.forceFailureForTest)throw new Error('forced shadow-only failure');const [ctx,candidates]=await Promise.all([buildPersonalizedRecommendationContext(childId),loadShadowLessonCandidates()]);const evaluated=candidates.map(c=>{const decisions=evaluateEligibility(c,ctx,o);const exclusions=decisions.filter(x=>!x.accepted).map(x=>x.filter);const scored=scoreShadowCandidate(c,ctx,o);return{...c,eligible:exclusions.length===0,score:scored.score,rank:null,positiveReasons:scored.positive,penalties:scored.penalties,exclusions,decisions,rejectedBy:exclusions[0]??null} as EvaluatedCandidate;});const accepted=evaluated.filter(x=>x.eligible).sort((a,b)=>b.score-a.score||a.lesson.id.localeCompare(b.lesson.id));accepted.forEach((x,i)=>x.rank=i+1);const rejected=evaluated.filter(x=>!x.eligible);const exclusions=rejected.flatMap(x=>x.exclusions).reduce((a,k)=>(a[k]=(a[k]??0)+1,a),{} as Record<string,number>);return{algorithmVersion:SHADOW_ALGORITHM_VERSION,architectureVersion:1,generatedAt:new Date().toISOString(),recommendation:accepted[0]??null,accepted,rejected,appliedFilters:['active','approval','entitlement','mapping','recommendation_eligibility','retirement','owner_decision','metadata_ready','communication','restrictions','prerequisites','high_scrutiny'],missingMetadata:candidates.filter(x=>x.missingMetadata.length).map(x=>({lessonId:x.lesson.id,title:x.lesson.title,fields:x.missingMetadata})),missingCurriculum:accepted.length?[]:['No eligible shadow recommendation for this context.'],summary:{evaluated:candidates.length,eligible:accepted.length,excluded:rejected.length,metadataSources:countMetadataSources(candidates),exclusions}};}
export async function inspectShadowRecommendation(childId:string,o:Pick<ShadowRecommendationOptions,'category'|'isPro'>&Partial<ShadowRecommendationOptions>){const production=await getCurrentProductionRecommendation(childId,o);try{const context=await buildPersonalizedRecommendationContext(childId);const shadow=await getShadowRecommendation(childId,{...o,skillArea:o.skillArea??production.skillArea,stageNumber:o.stageNumber??production.stageNumber});return{algorithmVersion:shadow.algorithmVersion,currentProductionRecommendation:production.lesson?{id:production.lesson.id,title:production.lesson.title}:null,shadowRecommendation:shadow.recommendation?{id:shadow.recommendation.lesson.id,title:shadow.recommendation.lesson.title,score:shadow.recommendation.score}:null,profileSummary:inspectPersonalizationProfile(context.profile),topCandidates:shadow.accepted.slice(0,o.limit??10).map(x=>({id:x.lesson.id,title:x.lesson.title,rank:x.rank,score:x.score,curriculum:x.curriculum,metadataSource:x.metadata.source,supportLevel:x.metadata.supportLevel,positiveReasons:x.positiveReasons,penalties:x.penalties})),summary:shadow.summary,missingCurriculum:shadow.missingCurriculum};}catch{return{algorithmVersion:SHADOW_ALGORITHM_VERSION,currentProductionRecommendation:production.lesson?{id:production.lesson.id,title:production.lesson.title}:null,shadowRecommendation:null,shadowError:'Shadow evaluation unavailable',productionUnaffected:true};}}
