import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

export const shareWeeklyReport = async (childName: string, sessionTotal: number, activityCount: number) => {
  const html = `
    <html>
      <body style="font-family: sans-serif; padding: 50px;">
        <h1 style="color: #007AFF;">ABA at Home: Weekly Progress</h1>
        <p><strong>Child:</strong> ${childName}</p>
        <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
        <hr />
        <div style="background: #F2F2F7; padding: 20px; border-radius: 10px;">
          <h2>Summary</h2>
          <p>Total Pairing Time: <strong>${sessionTotal} minutes</strong></p>
          <p>Activities Completed: <strong>${activityCount}</strong></p>
        </div>
        <footer style="margin-top: 50px; font-size: 12px; color: #8E8E93;">
          Generated by ABA at Home App
        </footer>
      </body>
    </html>
  `;

  const { uri } = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
};
