import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { approveProductionMetadata, canReapproveProductionMetadata, finalizeLessonAndPersonalization, generatePersonalizationDecisions, getMetadataHistory, getMetadataReviewRow, getProductionReviewDecisions, reviewProductionDecision, type LessonMetadataReviewRow, type MetadataHistoryRow, type ProductionReviewDecision } from '../../../lib/personalization/metadataReview';

const LABELS:Record<string,string>={communication:'Communication method',safety_material:'Materials and safety',prerequisite:'Earlier abilities',mastery:'Mastery relationship',duplicate_progression:'Duplicate or progression'};
const OPTIONS:Record<string,{label:string;outcome:string}[]>={
 communication:[{label:'Confirm recommendation',outcome:'confirm_recommendation'},{label:'Speech is required',outcome:'speech_required'},{label:'Allow alternate communication',outcome:'alternate_modes'},{label:'Needs more review',outcome:'needs_more_review'},{label:'Content issue — review lesson',outcome:'needs_content_review'}],
 safety_material:[{label:'Confirm reviewed',outcome:'human_confirmed'},{label:'Needs more review',outcome:'needs_more_review'},{label:'Content issue — review lesson',outcome:'needs_content_review'}],
 prerequisite:[{label:'Required',outcome:'required'},{label:'Helpful, not required',outcome:'helpful'},{label:'Not a prerequisite',outcome:'not_required'},{label:'Needs more review',outcome:'needs_more_review'},{label:'Content issue — review lesson',outcome:'needs_content_review'}],
 mastery:[{label:'Confirm specific scope',outcome:'confirm_scope'},{label:'Needs more review',outcome:'needs_more_review'}],
 duplicate_progression:[{label:'Intentional progression',outcome:'intentional_progression'},{label:'Intentional variant',outcome:'intentional_variant'},{label:'Likely duplicate',outcome:'likely_duplicate'},{label:'Needs content review',outcome:'needs_content_review'}],
};

export default function ProductionMetadataReview(){
 const {id}=useLocalSearchParams<{id:string}>();const router=useRouter();
 const [row,setRow]=useState<LessonMetadataReviewRow|null>(null);const [decisions,setDecisions]=useState<ProductionReviewDecision[]>([]);const [history,setHistory]=useState<MetadataHistoryRow[]>([]);const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!id)return;try{const [r,d,h]=await Promise.all([getMetadataReviewRow(id),getProductionReviewDecisions(id),getMetadataHistory(id)]);setRow(r);setDecisions(d);setHistory(h)}catch(e){Alert.alert('Unable to load',message(e))}},[id]);
 useEffect(()=>{void load()},[load]);
 const production=row?.lesson.quality_status==='approved'&&row.lesson.is_active;
 const unresolved=useMemo(()=>decisions.filter(d=>d.requires_human&&!['human_confirmed','human_edited'].includes(d.decision_status)),[decisions]);
 const contentIssues=decisions.filter(d=>d.decision_status==='content_dependent');const completed=decisions.filter(d=>d.decision_status!=='content_dependent'&&(!d.requires_human||['human_confirmed','human_edited'].includes(d.decision_status)));
 const canReapprove=row?canReapproveProductionMetadata(row,decisions):false;
 const decide=(d:ProductionReviewDecision,outcome:string)=>Alert.alert('Save this decision?',`${LABELS[d.decision_category]}: ${outcome.replaceAll('_',' ')}`,[{text:'Cancel',style:'cancel'},{text:'Save',onPress:async()=>{setBusy(true);try{const finalValue=d.decision_category==='prerequisite'&&outcome==='required'?{skill_code:d.candidate_value.suggested_skill_code}:{};await reviewProductionDecision(d.id,outcome,finalValue);await load()}catch(e){Alert.alert('Decision not saved',message(e))}finally{setBusy(false)}}}]);
 const generate=async()=>{if(!row)return;setBusy(true);try{await generatePersonalizationDecisions(row.lesson_id);await load()}catch(e){Alert.alert('Decisions not generated',message(e))}finally{setBusy(false)}};
 const approve=()=>{if(!row)return;const lessonId=row.lesson_id;Alert.alert('Finalize lesson approval?','Lesson content and personalization metadata will become approved together. The server will reject incomplete review.',[{text:'Cancel',style:'cancel'},{text:'Finalize atomically',onPress:async()=>{setBusy(true);try{await finalizeLessonAndPersonalization(lessonId);await load();Alert.alert('Approved','Lesson and personalization metadata were approved together.')}catch(e){Alert.alert('Not approved',message(e))}finally{setBusy(false)}}}])};
 const reapprove=()=>{if(!row||!canReapprove)return;Alert.alert('Reapprove personalization metadata?','Confirm that the corrected lesson content, personalization metadata, and balanced support level have been reviewed. The server will verify the current fingerprint and every lifecycle gate.',[{text:'Cancel',style:'cancel'},{text:'Reapprove Metadata',onPress:async()=>{setBusy(true);try{await approveProductionMetadata(row.id);await load();Alert.alert('Metadata reapproved','Personalization metadata is approved against the current lesson fingerprint.')}catch(e){Alert.alert('Metadata not reapproved',message(e))}finally{setBusy(false)}}}])};
 if(!row)return <View style={s.center}><ActivityIndicator color="#6D28D9"/></View>;
 return <SafeAreaView style={s.root}><ScrollView contentContainerStyle={s.content}>
  <View style={s.header}><TouchableOpacity onPress={()=>router.back()}><Ionicons name="arrow-back" size={24} color="#29145F"/></TouchableOpacity><View style={{flex:1}}><Text style={s.title}>{row.lesson.title}</Text><Text style={s.sub}>Current Production · Personalization review</Text></View></View>
  {!production&&<View style={s.blocked}><Text style={s.blockedTitle}>Hidden draft review</Text><Text style={s.body}>This lesson remains unavailable to parents while personalization decisions are reviewed. Final approval is atomic.</Text></View>}
  <Section title="Lesson summary"><Read label="What this lesson teaches" value={row.lesson.goal||row.lesson.description}/><Read label="Skill and level" value={`${row.lesson.skill_area} · ${row.lesson.stage_name} · ${row.lesson.difficulty}`}/><Read label="What the child does" value={row.lesson.expected_child_response}/><Read label="Materials" value={(row.lesson.materials??[]).join(' • ')||'No special materials'}/><TouchableOpacity style={s.link} onPress={()=>router.push({pathname:'/admin/lesson-review/[id]',params:{id:row.lesson_id}} as never)}><Text style={s.linkText}>View full lesson</Text><Ionicons name="arrow-forward" size={16} color="#6D28D9"/></TouchableOpacity></Section>
  <Section title="Personalization summary"><Read label="Target ability" value={plain(row.target_skill_code)}/><Read label="Communication supported" value={(row.supported_response_modes??[]).map(plain).join(', ')}/><Read label="Child needs this may match" value={(row.assessment_need_tags??[]).map(plain).join(', ')||'No special need tags'}/><Read label="Activity descriptors" value={(row.material_activity_tags??[]).map(plain).join(', ')||'None'}/><Read label="Human restrictions" value={(row.contraindication_tags??[]).map(plain).join(', ')||'None confirmed'}/></Section>
  {contentIssues.length>0&&<Section title={`Lesson content issues (${contentIssues.length})`}><Text style={s.contentWarning}>Metadata approval is blocked. These conflicts require lesson-level review; this screen will not rewrite the lesson.</Text>{contentIssues.map(d=><EvidenceDecision key={d.id} decision={d}/>)}</Section>}
  {decisions.length===0&&<Section title="Personalization decisions"><Text style={s.body}>Create the five canonical review decisions while this lesson remains hidden.</Text><TouchableOpacity style={s.approve} disabled={busy} onPress={generate}><Text style={s.approveText}>Generate Five Decisions</Text></TouchableOpacity></Section>}
  <Section title={`Decisions to make (${unresolved.length})`}>{unresolved.length===0?<Text style={s.ok}>{decisions.length===5?'All required decisions are resolved.':'Generate the canonical decision set to begin.'}</Text>:unresolved.map(d=><Decision key={d.id} decision={d} disabled={busy} onChoose={o=>decide(d,o)}/>)}</Section>
  <Section title={`Confirmed or deterministic (${completed.length})`}>{completed.map(d=><View key={d.id} style={s.done}><Ionicons name="checkmark-circle" size={18} color="#047857"/><View style={{flex:1}}><Text style={s.doneTitle}>{LABELS[d.decision_category]}</Text><Text style={s.small}>{d.plain_language_summary}</Text><Text style={s.provenance}>{d.provenance.replaceAll('_',' ')}{d.reviewed_at?` · ${new Date(d.reviewed_at).toLocaleString()}`:''}</Text></View></View>)}</Section>
  <Section title="Finish review"><Text style={s.body}>{production?(canReapprove?'All production reapproval gates are ready. Confirm the targeted content and metadata review to continue.':row.metadata_stale?'Save the reviewed lesson correction before metadata can be reapproved.':row.review_status==='approved'?'Production metadata is already approved and current.':'Production metadata does not currently satisfy every server-backed reapproval gate.'):contentIssues.length?'Lesson content review is required before finalization.':decisions.length!==5?'Exactly five decisions are required.':unresolved.length?`${unresolved.length} meaningful decision${unresolved.length===1?'':'s'} remain. Approval stays locked.`:!row.support_level_reviewed?'Support level must be reviewed individually.':row.content_review_status!=='approved'?'Content review must be confirmed.':'All gates are ready. The server will approve lesson and personalization together.'}</Text>{production?<TouchableOpacity style={[s.approve,(!canReapprove||busy)&&s.disabled]} disabled={!canReapprove||busy} onPress={reapprove}><Text style={s.approveText}>{row.review_status==='approved'?'Metadata Already Current':'Approve Production Metadata'}</Text></TouchableOpacity>:<TouchableOpacity style={[s.approve,(decisions.length!==5||unresolved.length>0||contentIssues.length>0||busy||!row.support_level_reviewed||row.content_review_status!=='approved')&&s.disabled]} disabled={decisions.length!==5||unresolved.length>0||contentIssues.length>0||busy||!row.support_level_reviewed||row.content_review_status!=='approved'} onPress={approve}><Text style={s.approveText}>Finalize Lesson + Personalization</Text></TouchableOpacity>}{busy&&<ActivityIndicator color="#6D28D9"/>}</Section>
  <Section title={`Audit history (${history.length})`}>{history.length?history.map(h=><View key={h.id} style={s.history}><Text style={s.doneTitle}>{h.action.replaceAll('_',' ')}</Text><Text style={s.small}>{new Date(h.created_at).toLocaleString()}</Text></View>):<Text style={s.small}>No metadata approval history yet. Individual decisions retain their own reviewer and timestamp.</Text>}</Section>
 </ScrollView></SafeAreaView>;
}
function Decision({decision,onChoose,disabled}:{decision:ProductionReviewDecision;onChoose:(outcome:string)=>void;disabled:boolean}){return <View style={s.decision}><Text style={s.decisionTitle}>{LABELS[decision.decision_category]}</Text><Text style={s.body}>{decision.plain_language_summary}</Text>{decision.prompt&&<Text style={s.prompt}>{decision.prompt}</Text>}<Evidence decision={decision}/>{decision.recommendation&&<View style={s.rec}><Text style={s.recTitle}>Suggested review — not selected</Text><Text style={s.small}>{decision.recommendation}</Text>{decision.rationale&&<Text style={s.rationale}>{decision.rationale}</Text>}</View>}<View style={s.options}>{(OPTIONS[decision.decision_category]??[]).map(o=><TouchableOpacity disabled={disabled} key={o.outcome} style={s.option} onPress={()=>onChoose(o.outcome)}><Text style={s.optionText}>{o.label}</Text></TouchableOpacity>)}</View></View>}
function EvidenceDecision({decision}:{decision:ProductionReviewDecision}){return <View style={s.decision}><Text style={s.decisionTitle}>{LABELS[decision.decision_category]}</Text><Text style={s.body}>{decision.plain_language_summary}</Text><Evidence decision={decision}/></View>}
function Evidence({decision}:{decision:ProductionReviewDecision}){return <>{(decision.evidence??[]).map((e,i)=><View key={`${e.field}-${i}`} style={s.evidence}><Text style={s.evidenceTitle}>Why this was classified · {e.field}</Text><Text style={s.small}>{e.why}</Text><Text style={s.quote}>{e.excerpt}</Text></View>)}</>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text>{children}</View>}
function Read({label,value}:{label:string;value?:string|null}){return <View style={s.read}><Text style={s.label}>{label}</Text><Text style={s.body}>{value||'—'}</Text></View>}
function plain(value:string|null|undefined){return value?.replaceAll('.',' › ').replaceAll('_',' ')||'—'}
function message(e:unknown){return e instanceof Error?e.message:'Unknown error'}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#FFF8F1'},center:{flex:1,alignItems:'center',justifyContent:'center'},content:{padding:20,paddingBottom:100},header:{flexDirection:'row',gap:14,alignItems:'center',marginBottom:16},title:{fontSize:22,fontWeight:'900',color:'#29145F'},sub:{color:'#64748B'},section:{backgroundColor:'#FFF',borderRadius:18,padding:16,marginBottom:12,borderWidth:1,borderColor:'#EDE9FE'},sectionTitle:{fontSize:17,fontWeight:'900',color:'#4C1D95',marginBottom:10},read:{marginBottom:12},label:{fontSize:11,fontWeight:'900',color:'#64748B',textTransform:'uppercase',marginBottom:4},body:{color:'#334155',fontWeight:'600',lineHeight:20},link:{flexDirection:'row',gap:6,alignItems:'center',marginTop:4},linkText:{color:'#6D28D9',fontWeight:'900'},blocked:{backgroundColor:'#FEF3C7',borderRadius:16,padding:14,marginBottom:12},blockedTitle:{color:'#92400E',fontWeight:'900'},decision:{borderTopWidth:1,borderTopColor:'#EDE9FE',paddingTop:14,marginTop:8},decisionTitle:{fontSize:15,fontWeight:'900',color:'#29145F',marginBottom:5},prompt:{color:'#1E293B',fontWeight:'900',marginTop:9},rec:{backgroundColor:'#F5F3FF',borderRadius:12,padding:11,marginTop:10},recTitle:{color:'#6D28D9',fontWeight:'900',marginBottom:3},rationale:{fontSize:11,color:'#64748B',marginTop:5},evidence:{backgroundColor:'#F8FAFC',borderRadius:10,padding:9,marginTop:8},evidenceTitle:{fontSize:11,fontWeight:'900',color:'#475569'},quote:{fontSize:11,color:'#64748B',fontStyle:'italic',marginTop:4},contentWarning:{color:'#B45309',fontWeight:'900',lineHeight:20},options:{gap:7,marginTop:11},option:{borderWidth:1,borderColor:'#7C3AED',borderRadius:11,padding:11},optionText:{color:'#6D28D9',fontWeight:'900',textAlign:'center'},done:{flexDirection:'row',gap:9,borderTopWidth:1,borderTopColor:'#F1F5F9',paddingVertical:9},doneTitle:{fontWeight:'900',color:'#334155'},small:{fontSize:12,color:'#64748B',lineHeight:17},provenance:{fontSize:10,color:'#047857',fontWeight:'800',marginTop:3,textTransform:'capitalize'},ok:{color:'#047857',fontWeight:'900'},approve:{backgroundColor:'#6D28D9',borderRadius:12,padding:13,alignItems:'center',marginTop:12},approveText:{color:'#FFF',fontWeight:'900'},disabled:{opacity:.35},history:{borderTopWidth:1,borderTopColor:'#F1F5F9',paddingVertical:8}});
