import { Ionicons } from '@expo/vector-icons';
import { Stack, useFocusEffect, useRouter } from 'expo-router';
import React, { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, BackHandler, Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { useChild } from '../../../lib/SelectedChildContext';
import { returnToActiveSearch } from '../../../lib/safety/elopementNavigation';
import { ELOPEMENT_COLORS as C } from '../../../lib/safety/elopementTheme';
import { loadEmergencyContacts, type SafetyEmergencyContact } from '../../../lib/safety/preparednessData';
import { getSafetyAccess } from '../../../lib/safety/safetyAccess';

export default function IncidentContactsScreen() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const { selectedChild } = useChild(); const childId = selectedChild?.id; const [contacts, setContacts] = useState<SafetyEmergencyContact[]>([]); const [loading, setLoading] = useState(true); const goBack = useCallback(() => returnToActiveSearch(router), [router]);
  useFocusEffect(useCallback(() => { const hardware = BackHandler.addEventListener('hardwareBackPress', () => { goBack(); return true; }); let active = true; void (async () => { try { if (!childId) return; const access = await getSafetyAccess(childId); if (!access.canViewSafetyProfile || !access.canParticipateInSafetyIncident) throw new Error('Unauthorized'); const items = await loadEmergencyContacts(childId); if (active) setContacts(items); } catch { if (active) Alert.alert('Contacts Unavailable', 'You don’t currently have access to these emergency contacts.'); } finally { if (active) setLoading(false); } })(); return () => { active = false; hardware.remove(); }; }, [childId, goBack]));
  const call = async (contact: SafetyEmergencyContact) => { if (!contact.phone) return; const url = `tel:${contact.phone.replace(/[^\d+*#,;]/g, '')}`; if (await Linking.canOpenURL(url)) await Linking.openURL(url); else Alert.alert('Calling isn’t available', `Use this number on a phone: ${contact.phone}`); };
  return <SafeAreaView style={styles.container}><Stack.Screen options={{ headerShown: false, gestureEnabled: false }} /><Pressable accessibilityRole="button" accessibilityLabel="Back to active search" hitSlop={14} onPress={goBack} style={[styles.back, { top: insets.top + 8 }]}><Ionicons name="chevron-back" size={24} color={C.text} accessible={false} pointerEvents="none" /></Pressable><ScrollView contentContainerStyle={styles.content}><Text accessibilityRole="header" style={styles.title}>Emergency Contacts</Text><Text style={styles.subtitle}>People your family may need to reach quickly.</Text>{loading ? <ActivityIndicator style={styles.loading} color={C.lavender} /> : !contacts.length ? <Text style={styles.empty}>No emergency contacts have been added for this child.</Text> : contacts.map((contact) => <View key={contact.id} style={styles.card}><View style={styles.heading}><Text style={styles.name}>{contact.name}</Text>{contact.isPrimary ? <Text style={styles.badge}>PRIMARY</Text> : null}</View>{contact.relationship ? <Text style={styles.relationship}>{contact.relationship}</Text> : null}{contact.phone ? <Pressable accessibilityRole="button" accessibilityLabel={`Call ${contact.name}${contact.relationship ? `, ${contact.relationship}` : ''}`} onPress={() => void call(contact)} style={styles.call}><Ionicons name="call" size={20} color={C.backgroundDeep} accessible={false} /><Text style={styles.callText}>{contact.phone}</Text></Pressable> : null}{contact.email ? <Text style={styles.email}>{contact.email}</Text> : null}</View>)}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: C.background }, back: { position: 'absolute', zIndex: 100, elevation: 20, left: 18, width: 46, height: 46, borderRadius: 23, alignItems: 'center', justifyContent: 'center', backgroundColor: C.surface, borderWidth: 1, borderColor: C.border }, content: { paddingHorizontal: 20, paddingTop: 94, paddingBottom: 90 }, title: { color: C.text, fontSize: 31, lineHeight: 38, fontWeight: '900' }, subtitle: { marginTop: 8, color: C.textMuted, fontSize: 15, lineHeight: 23, fontWeight: '600' }, loading: { marginTop: 50 }, empty: { marginTop: 24, padding: 18, borderRadius: 20, color: C.textMuted, fontSize: 15, lineHeight: 22, backgroundColor: C.surface }, card: { marginTop: 14, padding: 18, borderRadius: 22, backgroundColor: C.surface, borderWidth: 1, borderColor: C.border }, heading: { flexDirection: 'row', gap: 10, alignItems: 'center' }, name: { flex: 1, color: C.text, fontSize: 19, fontWeight: '900' }, badge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 10, color: C.lavender, backgroundColor: C.lavenderSoft, fontSize: 10, fontWeight: '900' }, relationship: { marginTop: 4, color: C.textMuted, fontSize: 14, fontWeight: '700' }, call: { minHeight: 56, marginTop: 14, paddingHorizontal: 16, borderRadius: 28, flexDirection: 'row', gap: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: C.lightSurface }, callText: { color: C.lightText, fontSize: 16, fontWeight: '900' }, email: { marginTop: 11, color: C.textMuted, fontSize: 14, lineHeight: 20 } });
