import { Ionicons } from '@expo/vector-icons';
import { Stack, useFocusEffect, useRouter } from 'expo-router';
import React, { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, BackHandler, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { useChild } from '../../../lib/SelectedChildContext';
import { returnToActiveSearch } from '../../../lib/safety/elopementNavigation';
import { ELOPEMENT_COLORS as C } from '../../../lib/safety/elopementTheme';
import { loadLocationSources, type SafetyLocationSource } from '../../../lib/safety/preparednessData';
import { getSafetyAccess } from '../../../lib/safety/safetyAccess';
import { launchLocationProvider, resolveLocationProvider } from '../../../lib/safety/locationProviders';

export default function IncidentLocationToolsScreen() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const { selectedChild } = useChild(); const child = selectedChild as (typeof selectedChild & { first_name?: string }) | null; const childId = child?.id; const childName = child?.child_name || child?.name || child?.first_name || 'your child'; const [sources, setSources] = useState<SafetyLocationSource[]>([]); const [loading, setLoading] = useState(true); const goBack = useCallback(() => returnToActiveSearch(router), [router]);
  useFocusEffect(useCallback(() => { const hardware = BackHandler.addEventListener('hardwareBackPress', () => { goBack(); return true; }); let active = true; void (async () => { try { if (!childId) return; const access = await getSafetyAccess(childId); if (!access.canViewSafetyProfile || !access.canParticipateInSafetyIncident) throw new Error('Unauthorized'); const items = await loadLocationSources(childId); if (active) setSources(items); } catch { if (active) Alert.alert('Location Tools Unavailable', 'You don’t currently have access to these location tools.'); } finally { if (active) setLoading(false); } })(); return () => { active = false; hardware.remove(); }; }, [childId, goBack]));
  const launch = (source: SafetyLocationSource) => launchLocationProvider(source, childName);
  return <SafeAreaView style={styles.container}><Stack.Screen options={{ headerShown: false, gestureEnabled: false }} /><Pressable accessibilityRole="button" accessibilityLabel="Back to active search" hitSlop={14} onPress={goBack} style={[styles.back, { top: insets.top + 8 }]}><Ionicons name="chevron-back" size={24} color={C.text} accessible={false} pointerEvents="none" /></Pressable><ScrollView contentContainerStyle={styles.content}><Text accessibilityRole="header" style={styles.title}>Location Support</Text><Text style={styles.intro}>Check {childName}’s location using the service your family already uses.</Text><Text style={styles.disclosure}>ABA at Home opens your connected location service. Location information comes from that provider, not ABA at Home.</Text>{loading ? <ActivityIndicator style={styles.loading} color={C.lavender} /> : !sources.length ? <Text style={styles.empty}>No location support has been added for this child.</Text> : sources.map((source) => { const provider = resolveLocationProvider(source); const appName = source.providerName || provider.defaultAppName || provider.displayName; const isManual = provider.launchStrategy === 'manual'; return <View key={source.id} style={styles.card}><Text style={styles.name}>{source.label}</Text><Text style={styles.meta}>{appName}</Text><Text style={styles.device}>{provider.displayName}</Text>{source.notes ? <Text style={styles.notes}>{source.notes}</Text> : null}<Pressable accessibilityRole="button" accessibilityLabel={`${provider.actionLabel} location service`} accessibilityHint={isManual ? 'Shows your family’s saved instructions.' : `Opens the external ${provider.defaultAppName || provider.displayName} service used by your family.`} onPress={() => void launch(source)} style={styles.open}><Ionicons name={isManual ? 'information-circle-outline' : 'open-outline'} size={20} color={C.backgroundDeep} accessible={false} /><Text style={styles.openText}>{provider.actionLabel}</Text></Pressable></View>; })}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: C.background }, back: { position: 'absolute', zIndex: 100, elevation: 20, left: 18, width: 46, height: 46, borderRadius: 23, alignItems: 'center', justifyContent: 'center', backgroundColor: C.surface, borderWidth: 1, borderColor: C.border }, content: { paddingHorizontal: 20, paddingTop: 94, paddingBottom: 90 }, title: { color: C.text, fontSize: 31, lineHeight: 38, fontWeight: '900' }, intro: { marginTop: 12, color: C.text, fontSize: 17, lineHeight: 25, fontWeight: '700' }, disclosure: { marginTop: 8, color: C.textMuted, fontSize: 13, lineHeight: 20, fontWeight: '600' }, loading: { marginTop: 50 }, empty: { marginTop: 24, padding: 18, borderRadius: 20, color: C.textMuted, fontSize: 15, lineHeight: 22, backgroundColor: C.surface }, card: { marginTop: 18, padding: 18, borderRadius: 22, backgroundColor: C.surface, borderWidth: 1, borderColor: C.border }, name: { color: C.text, fontSize: 19, fontWeight: '900' }, meta: { marginTop: 5, color: C.textMuted, fontSize: 15, lineHeight: 21, fontWeight: '800' }, device: { marginTop: 3, color: C.textSubtle, fontSize: 13, lineHeight: 19, fontWeight: '600' }, notes: { marginTop: 10, color: C.textMuted, fontSize: 14, lineHeight: 21 }, open: { minHeight: 56, marginTop: 14, paddingHorizontal: 16, borderRadius: 28, flexDirection: 'row', gap: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: C.lightSurface }, openText: { flexShrink: 1, color: C.lightText, fontSize: 15, lineHeight: 21, fontWeight: '900', textAlign: 'center' } });
